
# --- !Ups

create table "GAMES" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"version" INTEGER DEFAULT 1 NOT NULL,"description" VARCHAR NOT NULL,"location" VARCHAR NOT NULL,"operatorId" INTEGER NOT NULL,"created" TIMESTAMP NOT NULL,"updated" TIMESTAMP DEFAULT {ts '2013-05-31 02:30:48.519'} NOT NULL,"startTime" TIMESTAMP NOT NULL,"endTime" TIMESTAMP NOT NULL,"started" TIMESTAMP,"ended" TIMESTAMP,"winning" VARCHAR DEFAULT 'max_points' NOT NULL,"nWins" INTEGER DEFAULT 1 NOT NULL,"difficulty" VARCHAR DEFAULT 'easy' NOT NULL,"maxPlayers" INTEGER DEFAULT 1000000 NOT NULL,"awards" VARCHAR NOT NULL,"status" VARCHAR DEFAULT 'project' NOT NULL,"image" VARCHAR DEFAULT 'games/gameicon.png' NOT NULL,"tasksNo" INTEGER DEFAULT 0 NOT NULL);
create table "OPERATORS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"login" VARCHAR NOT NULL,"pass_hash" VARCHAR NOT NULL);
create table "SKINS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"gameId" INTEGER NOT NULL,"icon" VARCHAR DEFAULT 'games/gameicon.png' NOT NULL);
create table "TASKS" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"gameId" INTEGER NOT NULL,"version" INTEGER DEFAULT 1 NOT NULL,"name" VARCHAR NOT NULL,"description" VARCHAR NOT NULL,"deadline" TIMESTAMP NOT NULL,"maxpoints" INTEGER NOT NULL,"maxattempts" INTEGER NOT NULL);
alter table "GAMES" add constraint "OP_FK" foreign key("operatorId") references "OPERATORS"("id") on update NO ACTION on delete NO ACTION;
alter table "SKINS" add constraint "GM_FK" foreign key("gameId") references "GAMES"("id") on update NO ACTION on delete NO ACTION;
alter table "TASKS" add constraint "GMT_FK" foreign key("gameId") references "GAMES"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

