//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrbanGame.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UrbanGame.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon game.
        /// </summary>
        public static string AbandonGame {
            get {
                return ResourceManager.GetString("AbandonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is urban game? That&apos;s great What is urban game? That&apos;s great question, well it&apos;s something!
        ///                               well it&apos;s something!.
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultricies turpis et augue pretium nec rhoncus odio congue. Duis faucibus accumsan eros sed volutpat. Nulla lorem urna, adipiscing non euismod non, egestas sit amet ligula. Maecenas condimentum tellus lacus, ornare mattis lacus..
        /// </summary>
        public static string AboutText2 {
            get {
                return ResourceManager.GetString("AboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accomplished.
        /// </summary>
        public static string Accomplished {
            get {
                return ResourceManager.GetString("Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT CREATED!.
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think this is the right spot, please submit your coordinates to check..
        /// </summary>
        public static string AnswerGPS {
            get {
                return ResourceManager.GetString("AnswerGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any active game..
        /// </summary>
        public static string AnyGame {
            get {
                return ResourceManager.GetString("AnyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below 1 m.
        /// </summary>
        public static string BelowMinute {
            get {
                return ResourceManager.GetString("BelowMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bonus task found.
        /// </summary>
        public static string BonusTask {
            get {
                return ResourceManager.GetString("BonusTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string ByOperator {
            get {
                return ResourceManager.GetString("ByOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BY.
        /// </summary>
        public static string ByOperatorUpCase {
            get {
                return ResourceManager.GetString("ByOperatorUpCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose one and join in..
        /// </summary>
        public static string ChooseAndJoin {
            get {
                return ResourceManager.GetString("ChooseAndJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed all tasks, but few tasks could be done better. Try to repeat them in order to gain more points..
        /// </summary>
        public static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmation email has been sent.
        /// </summary>
        public static string ConfirmationEmail {
            get {
                return ResourceManager.GetString("ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORRECT!.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating account.
        /// </summary>
        public static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current rank:.
        /// </summary>
        public static string CurrentRank {
            get {
                return ResourceManager.GetString("CurrentRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution sent, but results will be available later..
        /// </summary>
        public static string DelayedSolution {
            get {
                return ResourceManager.GetString("DelayedSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to difficulty:.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration:.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter login!.
        /// </summary>
        public static string EmptyLogin {
            get {
                return ResourceManager.GetString("EmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message can&apos;t be empty!.
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter password!.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end:.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while joining the game..
        /// </summary>
        public static string ErrorJoiningGame {
            get {
                return ResourceManager.GetString("ErrorJoiningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while leaving the game..
        /// </summary>
        public static string ErrorLeavingGame {
            get {
                return ResourceManager.GetString("ErrorLeavingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game details have changed. Tap to see differences..
        /// </summary>
        public static string GameChangedToast {
            get {
                return ResourceManager.GetString("GameChangedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end:.
        /// </summary>
        public static string GameEnd {
            get {
                return ResourceManager.GetString("GameEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMES.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games.
        /// </summary>
        public static string GamesLowCase {
            get {
                return ResourceManager.GetString("GamesLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start:.
        /// </summary>
        public static string GameStart {
            get {
                return ResourceManager.GetString("GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is over. Tap to see your result..
        /// </summary>
        public static string GameStateChangedToast {
            get {
                return ResourceManager.GetString("GameStateChangedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string GameStateInactive {
            get {
                return ResourceManager.GetString("GameStateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joined.
        /// </summary>
        public static string GameStateJoined {
            get {
                return ResourceManager.GetString("GameStateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lost.
        /// </summary>
        public static string GameStateLost {
            get {
                return ResourceManager.GetString("GameStateLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GameStateNone {
            get {
                return ResourceManager.GetString("GameStateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to won.
        /// </summary>
        public static string GameStateWon {
            get {
                return ResourceManager.GetString("GameStateWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game type:.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete all tasks first.
        /// </summary>
        public static string GameTypeRace {
            get {
                return ResourceManager.GetString("GameTypeRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gather as many points as possible.
        /// </summary>
        public static string GameTypeScoreAttack {
            get {
                return ResourceManager.GetString("GameTypeScoreAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high scores.
        /// </summary>
        public static string HighScores {
            get {
                return ResourceManager.GetString("HighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string Incorrect {
            get {
                return ResourceManager.GetString("Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email!.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or login.
        /// </summary>
        public static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join in.
        /// </summary>
        public static string JoinIn {
            get {
                return ResourceManager.GetString("JoinIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose one and join into..
        /// </summary>
        public static string JoinOneGame {
            get {
                return ResourceManager.GetString("JoinOneGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to the Urban Game or Log in!.
        /// </summary>
        public static string JoinOrLogIn {
            get {
                return ResourceManager.GetString("JoinOrLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in!.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in.
        /// </summary>
        public static string LogginIn {
            get {
                return ResourceManager.GetString("LogginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login has been already used.
        /// </summary>
        public static string LoginUnavailable {
            get {
                return ResourceManager.GetString("LoginUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my games.
        /// </summary>
        public static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string Nearby {
            get {
                return ResourceManager.GetString("Nearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task is available. Tap to see it..
        /// </summary>
        public static string NewTaskToast {
            get {
                return ResourceManager.GetString("NewTaskToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next instructions has been sent to provided e-mail address.
        /// </summary>
        public static string NextInstructions {
            get {
                return ResourceManager.GetString("NextInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparently you don&apos;t play in any game..
        /// </summary>
        public static string NoGamesPlaying {
            get {
                return ResourceManager.GetString("NoGamesPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not tasks at this point, try later or try to connect from different area of the city to receive hidden bonus tasks..
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in..
        /// </summary>
        public static string NotLogged {
            get {
                return ResourceManager.GetString("NotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not repeatable.
        /// </summary>
        public static string NotRepeatable {
            get {
                return ResourceManager.GetString("NotRepeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT SO GREAT!.
        /// </summary>
        public static string NotSoGreat {
            get {
                return ResourceManager.GetString("NotSoGreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password recovery.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to players:.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to see list of your games..
        /// </summary>
        public static string PleaseLog {
            get {
                return ResourceManager.GetString("PleaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p..
        /// </summary>
        public static string PointsShort {
            get {
                return ResourceManager.GetString("PointsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POINTS:.
        /// </summary>
        public static string PointsUpCase {
            get {
                return ResourceManager.GetString("PointsUpCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous games.
        /// </summary>
        public static string PreviousGames {
            get {
                return ResourceManager.GetString("PreviousGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prizes.
        /// </summary>
        public static string Prizes {
            get {
                return ResourceManager.GetString("Prizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide e-mail address connected with your account to recover your password..
        /// </summary>
        public static string ProvideEmail {
            get {
                return ResourceManager.GetString("ProvideEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quests.
        /// </summary>
        public static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refreshing.
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeatable.
        /// </summary>
        public static string Repeatable {
            get {
                return ResourceManager.GetString("Repeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter twice the same password.
        /// </summary>
        public static string RepeatYourPassword {
            get {
                return ResourceManager.GetString("RepeatYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report task.
        /// </summary>
        public static string ReportTask {
            get {
                return ResourceManager.GetString("ReportTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high scores.
        /// </summary>
        public static string Scores {
            get {
                return ResourceManager.GetString("Scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH GAME.
        /// </summary>
        public static string SearchGame {
            get {
                return ResourceManager.GetString("SearchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more answers..
        /// </summary>
        public static string SelectAnswers {
            get {
                return ResourceManager.GetString("SelectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending.
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service timeout.
        /// </summary>
        public static string ServiceTimeout {
            get {
                return ResourceManager.GetString("ServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution status has changed to.
        /// </summary>
        public static string SolutionStatusChanged {
            get {
                return ResourceManager.GetString("SolutionStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start:.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task was cancelled..
        /// </summary>
        public static string TaskCancelled {
            get {
                return ResourceManager.GetString("TaskCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task details have changed. Tap to see differences..
        /// </summary>
        public static string TaskChangedToast {
            get {
                return ResourceManager.GetString("TaskChangedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task becomes active after complete another tasks..
        /// </summary>
        public static string TaskInactive {
            get {
                return ResourceManager.GetString("TaskInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME LEFT:.
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO END.
        /// </summary>
        public static string ToEnd {
            get {
                return ResourceManager.GetString("ToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to end.
        /// </summary>
        public static string ToEndLowCase {
            get {
                return ResourceManager.GetString("ToEndLowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to start.
        /// </summary>
        public static string ToStart {
            get {
                return ResourceManager.GetString("ToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can retry or try again later.
        /// </summary>
        public static string TryLater {
            get {
                return ResourceManager.GetString("TryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefinied.
        /// </summary>
        public static string Undefinied {
            get {
                return ResourceManager.GetString("Undefinied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviced returned unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URBAN.
        /// </summary>
        public static string Urban {
            get {
                return ResourceManager.GetString("Urban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will contact with you.
        /// </summary>
        public static string WeWillContact {
            get {
                return ResourceManager.GetString("WeWillContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WRONG!.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost!.
        /// </summary>
        public static string YouLost {
            get {
                return ResourceManager.GetString("YouLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won!.
        /// </summary>
        public static string YouWon {
            get {
                return ResourceManager.GetString("YouWon", resourceCulture);
            }
        }
    }
}
